/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Ismasant
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
        this.setTitle("Congreso UES Ixtlahuaca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUno = new javax.swing.JMenuItem();
        jMenuItemDos = new javax.swing.JMenuItem();
        jMenuItemTres = new javax.swing.JMenuItem();
        jMenuItemCuatro = new javax.swing.JMenuItem();
        jMenuItemCinco = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemTabla = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItemUno.setText("Usuarios");
        jMenuItemUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUno);

        jMenuItemDos.setText("Ponentes");
        jMenuItemDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDos);

        jMenuItemTres.setText("Actividad");
        jMenuItemTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTres);

        jMenuItemCuatro.setText("Docente");
        jMenuItemCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCuatroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCuatro);

        jMenuItemCinco.setText("Producto");
        jMenuItemCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCincoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCinco);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Otros");

        jMenuItemTabla.setText("Tablas");
        jMenuItemTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTabla);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnoActionPerformed
        // TODO add your handling code here:
        
        frmusuario form =new frmusuario();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemUnoActionPerformed

    private void jMenuItemDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDosActionPerformed
        // TODO add your handling code here:
        frmponente form =new frmponente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemDosActionPerformed

    private void jMenuItemTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaActionPerformed
        // TODO add your handling code here:
        // Tabla form =new Tabla();
        //escritorio.add(form);
        //form.toFront();
        //form.setVisible(true);
    }//GEN-LAST:event_jMenuItemTablaActionPerformed

    private void jMenuItemCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCuatroActionPerformed
        // TODO add your handling code here:
           frmdocente form =new frmdocente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCuatroActionPerformed

    private void jMenuItemTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTresActionPerformed
        // TODO add your handling code here:
          frmactividad form =new frmactividad();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemTresActionPerformed

    private void jMenuItemCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCincoActionPerformed
        // TODO add your handling code here:
        frmproducto form =new frmproducto();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemCincoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCinco;
    private javax.swing.JMenuItem jMenuItemCuatro;
    private javax.swing.JMenuItem jMenuItemDos;
    private javax.swing.JMenuItem jMenuItemTabla;
    private javax.swing.JMenuItem jMenuItemTres;
    private javax.swing.JMenuItem jMenuItemUno;
    // End of variables declaration//GEN-END:variables
}
